/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppInterviewsNewRouteImport } from './routes/_app/interviews.new'
import { Route as AppInterviewsIdPlanRouteImport } from './routes/_app/interviews.$id.plan'
import { Route as AppInterviewsIdReportRouteImport } from './routes/_app/interviews.$id.report'
import { Route as AppInterviewsIdSessionRouteImport } from './routes/_app/interviews.$id.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsNewRoute = AppInterviewsNewRouteImport.update({
  id: '/interviews/new',
  path: '/interviews/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdPlanRoute = AppInterviewsIdPlanRouteImport.update({
  id: '/interviews/$id/plan',
  path: '/interviews/$id/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdReportRoute = AppInterviewsIdReportRouteImport.update({
  id: '/interviews/$id/report',
  path: '/interviews/$id/report',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdSessionRoute = AppInterviewsIdSessionRouteImport.update({
  id: '/interviews/$id/session',
  path: '/interviews/$id/session',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/interviews/$id/plan': typeof AppInterviewsIdPlanRoute
  '/interviews/$id/report': typeof AppInterviewsIdReportRoute
  '/interviews/$id/session': typeof AppInterviewsIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/interviews/new': typeof AppInterviewsNewRoute
  '/interviews/$id/plan': typeof AppInterviewsIdPlanRoute
  '/interviews/$id/report': typeof AppInterviewsIdReportRoute
  '/interviews/$id/session': typeof AppInterviewsIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/interviews/new': typeof AppInterviewsNewRoute
  '/_app/interviews/$id/plan': typeof AppInterviewsIdPlanRoute
  '/_app/interviews/$id/report': typeof AppInterviewsIdReportRoute
  '/_app/interviews/$id/session': typeof AppInterviewsIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/interviews/new'
    | '/interviews/$id/plan'
    | '/interviews/$id/report'
    | '/interviews/$id/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/interviews/new'
    | '/interviews/$id/plan'
    | '/interviews/$id/report'
    | '/interviews/$id/session'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/interviews/new'
    | '/_app/interviews/$id/plan'
    | '/_app/interviews/$id/report'
    | '/_app/interviews/$id/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/new': {
      id: '/_app/interviews/new'
      path: '/interviews/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof AppInterviewsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/$id/plan': {
      id: '/_app/interviews/$id/plan'
      path: '/interviews/$id/plan'
      fullPath: '/interviews/$id/plan'
      preLoaderRoute: typeof AppInterviewsIdPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/$id/report': {
      id: '/_app/interviews/$id/report'
      path: '/interviews/$id/report'
      fullPath: '/interviews/$id/report'
      preLoaderRoute: typeof AppInterviewsIdReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews/$id/session': {
      id: '/_app/interviews/$id/session'
      path: '/interviews/$id/session'
      fullPath: '/interviews/$id/session'
      preLoaderRoute: typeof AppInterviewsIdSessionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppInterviewsNewRoute: typeof AppInterviewsNewRoute
  AppInterviewsIdPlanRoute: typeof AppInterviewsIdPlanRoute
  AppInterviewsIdReportRoute: typeof AppInterviewsIdReportRoute
  AppInterviewsIdSessionRoute: typeof AppInterviewsIdSessionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppInterviewsNewRoute: AppInterviewsNewRoute,
  AppInterviewsIdPlanRoute: AppInterviewsIdPlanRoute,
  AppInterviewsIdReportRoute: AppInterviewsIdReportRoute,
  AppInterviewsIdSessionRoute: AppInterviewsIdSessionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
