/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AgentRunsRouteImport } from './routes/agent-runs'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as DisruptionsIndexRouteImport } from './routes/disruptions.index'
import { Route as DisruptionsIdRouteImport } from './routes/disruptions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DisruptionsIndexRoute = DisruptionsIndexRouteImport.update({
  id: '/disruptions/',
  path: '/disruptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisruptionsIdRoute = DisruptionsIdRouteImport.update({
  id: '/disruptions/$id',
  path: '/disruptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agent-runs': typeof AgentRunsRoute
  '/compare': typeof CompareRoute
  '/network': typeof NetworkRoute
  '/orders': typeof OrdersRoute
  '/disruptions/$id': typeof DisruptionsIdRoute
  '/disruptions/': typeof DisruptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agent-runs': typeof AgentRunsRoute
  '/compare': typeof CompareRoute
  '/network': typeof NetworkRoute
  '/orders': typeof OrdersRoute
  '/disruptions/$id': typeof DisruptionsIdRoute
  '/disruptions': typeof DisruptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agent-runs': typeof AgentRunsRoute
  '/compare': typeof CompareRoute
  '/network': typeof NetworkRoute
  '/orders': typeof OrdersRoute
  '/disruptions/$id': typeof DisruptionsIdRoute
  '/disruptions/': typeof DisruptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/agent-runs'
    | '/compare'
    | '/network'
    | '/orders'
    | '/disruptions/$id'
    | '/disruptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/agent-runs'
    | '/compare'
    | '/network'
    | '/orders'
    | '/disruptions/$id'
    | '/disruptions'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/agent-runs'
    | '/compare'
    | '/network'
    | '/orders'
    | '/disruptions/$id'
    | '/disruptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AgentRunsRoute: typeof AgentRunsRoute
  CompareRoute: typeof CompareRoute
  NetworkRoute: typeof NetworkRoute
  OrdersRoute: typeof OrdersRoute
  DisruptionsIdRoute: typeof DisruptionsIdRoute
  DisruptionsIndexRoute: typeof DisruptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs': {
      id: '/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disruptions/': {
      id: '/disruptions/'
      path: '/disruptions'
      fullPath: '/disruptions/'
      preLoaderRoute: typeof DisruptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disruptions/$id': {
      id: '/disruptions/$id'
      path: '/disruptions/$id'
      fullPath: '/disruptions/$id'
      preLoaderRoute: typeof DisruptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AgentRunsRoute: AgentRunsRoute,
  CompareRoute: CompareRoute,
  NetworkRoute: NetworkRoute,
  OrdersRoute: OrdersRoute,
  DisruptionsIdRoute: DisruptionsIdRoute,
  DisruptionsIndexRoute: DisruptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
