/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentWorkflowRouteImport } from './routes/agent-workflow'
import { Route as CapstoneDeliverablesRouteImport } from './routes/capstone-deliverables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkflowRoute = AgentWorkflowRouteImport.update({
  id: '/agent-workflow',
  path: '/agent-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const CapstoneDeliverablesRoute = CapstoneDeliverablesRouteImport.update({
  id: '/capstone-deliverables',
  path: '/capstone-deliverables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/capstone-deliverables': typeof CapstoneDeliverablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/capstone-deliverables': typeof CapstoneDeliverablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/capstone-deliverables': typeof CapstoneDeliverablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/agent-workflow' | '/capstone-deliverables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/agent-workflow' | '/capstone-deliverables'
  id: '__root__' | '/' | '/about' | '/agent-workflow' | '/capstone-deliverables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentWorkflowRoute: typeof AgentWorkflowRoute
  CapstoneDeliverablesRoute: typeof CapstoneDeliverablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-workflow': {
      id: '/agent-workflow'
      path: '/agent-workflow'
      fullPath: '/agent-workflow'
      preLoaderRoute: typeof AgentWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capstone-deliverables': {
      id: '/capstone-deliverables'
      path: '/capstone-deliverables'
      fullPath: '/capstone-deliverables'
      preLoaderRoute: typeof CapstoneDeliverablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentWorkflowRoute: AgentWorkflowRoute,
  CapstoneDeliverablesRoute: CapstoneDeliverablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
